LOAD DATA INFILE "/home/cloudera/PDA_PROJECT_OLIST/PROCESSED/m_geo_location.csv" INTO TABLE Olist.geo_location COLUMNS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
