LOAD DATA INFILE "/home/cloudera/PDA_PROJECT_OLIST/PROCESSED/m_products_data.csv" INTO TABLE Olist.product COLUMNS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

